// Generated by CoffeeScript 1.4.0

define(function(require, exports) {
  var all, alpha;
  alpha = 'qwertyuiopasdfghjklzxcvbnm';
  all = '`1234567890-=~!@#$%^&*()_+ ';
  all += alpha;
  all += alpha.toUpperCase();
  all += '[]\\{}|;:"\',./<>?';
  exports.all = all.split('');
});
