// Generated by CoffeeScript 1.4.0

define(function(require, exports) {
  var caret, draw, escape, isArr, isStr, notArr, show;
  show = function() {};
  isArr = Array.isArray;
  isStr = function(item) {
    return (typeof item) === 'string';
  };
  notArr = function(item) {
    return !(isArr(item));
  };
  escape = function(item) {
    return item.replace(/\s/g, '&nbsp;');
  };
  caret = '<span id="caret"> </span>';
  exports.draw = draw = function(list, compact) {
    var html, inline;
    html = '';
    inline = !((list.every(notArr)) && compact) ? '' : ' class="inline"';
    list.forEach(function(item) {
      var compact_child;
      compact_child = list.length < 7;
      return html += isArr(item) ? draw(item, compact_child) : isStr(item) ? "<code>" + (item.replace(/\t/, caret)) + "</code>" : "<code>" + (escape(item)) + "</code>";
    });
    return "<pre" + inline + ">" + html + "</pre>";
  };
  exports.render = function(list, elem) {
    var caret_elem, height, scrollTop, top;
    elem.innerHTML = draw(list);
    caret_elem = elem.querySelector('#caret');
    top = caret_elem.offsetTop - elem.offsetTop;
    height = elem.offsetHeight;
    scrollTop = elem.scrollTop;
    show(caret_elem.offsetTop, elem.offsetTop, scrollTop);
    if (!((top > scrollTop) && (top < scrollTop + height))) {
      return elem.scrollTop = top - height / 2;
    }
  };
});
