// Generated by CoffeeScript 1.3.3
var all, alpha;

alpha = 'qwertyuiopasdfghjklzxcvbnm';

all = '`1234567890-=~!@#$%^&*()_+ ';

all += alpha;

all += alpha.toUpperCase();

all += '[]\\{}|;:"\',./<>?';

exports.all = alpha.split('');
