// Generated by CoffeeScript 1.3.3
var copy, input,
  __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

input = '<input id="input"/>';

copy = function(json) {
  return JSON.parse(JSON.stringify(json));
};

exports.editor = function(elem) {
  var add_history, alphabet, check, choice, create_block, ctrl_c, ctrl_v, ctrl_x, ctrl_y, ctrl_z, do_render, focused, history, insert_blank, insert_char, key, list, move_down, move_left, move_right, move_up, on_update, render, reset_history, ret, tool, _ref;
  _ref = require('./functions.js'), insert_char = _ref.insert_char, insert_blank = _ref.insert_blank, move_left = _ref.move_left, move_right = _ref.move_right, move_up = _ref.move_up, move_down = _ref.move_down, create_block = _ref.create_block, ctrl_x = _ref.ctrl_x, ctrl_c = _ref.ctrl_c, ctrl_v = _ref.ctrl_v, ctrl_z = _ref.ctrl_z, ctrl_y = _ref.ctrl_y, add_history = _ref.add_history, reset_history = _ref.reset_history;
  tool = {
    err: function(info) {
      throw new Error(info);
    }
  };
  (check = function() {
    if (typeof $ === "undefined" || $ === null) {
      tool.err('I need jQuery!');
    }
    if (elem == null) {
      return tool.err('need a elem!');
    }
  })();
  ret = {};
  list = [['\t']];
  elem = $(elem);
  focused = false;
  history = {
    all: [['\t']],
    now: 0
  };
  ret.reset_history = function(list) {
    return history = reset_history(history, list);
  };
  ret.val = function(value) {
    if (value != null) {
      return list = value;
    } else {
      return list;
    }
  };
  render = require('./renderer.js').render;
  on_update = [];
  ret.update = function(f) {
    return on_update.push(f);
  };
  ret.render = do_render = function() {
    render(list, elem);
    return on_update.forEach(function(f) {
      return f();
    });
  };
  elem.click(function(e) {
    focused = true;
    elem.css({
      opacity: 1
    });
    e.preventDefault();
    return false;
  });
  $(window).click(function() {
    elem.css({
      opacity: 0.4
    });
    return focused = false;
  });
  alphabet = require('./alphabet.js').all;
  $('body').keypress(function(e) {
    var char;
    if (focused) {
      char = String.fromCharCode(e.keyCode);
      if (__indexOf.call(alphabet, char) >= 0) {
        list = insert_char(list, char);
        history = add_history(copy(history), copy(list));
        return do_render();
      }
    }
  });
  choice = require('./control.js').choice;
  $('body').keydown(function(e) {
    var code;
    if (focused) {
      code = e.keyCode;
      if (choice[code] != null) {
        list = choice[code](list);
        history = add_history(copy(history), copy(list));
        do_render();
        return e.preventDefault();
      }
    }
  });
  key = new Kibo;
  key.down('ctrl i', function() {
    if (focused) {
      $('#caret').after(input).remove();
      focused = false;
      $('#input').focus().keydown(function(e) {
        if (e.keyCode === 13) {
          focused = true;
          list = insert_char(list, $('#input').val());
          do_render();
          e.preventDefault();
          return false;
        }
      });
      return false;
    }
  });
  key.down('ctrl x', function() {
    list = ctrl_x(list);
    do_render();
    return false;
  });
  key.down('ctrl c', function() {
    list = ctrl_c(list);
    do_render();
    return false;
  });
  key.down('ctrl v', function() {
    list = ctrl_v(list);
    do_render();
    return false;
  });
  key.down('ctrl z', function() {
    show('z:', history);
    list = ctrl_z(history);
    do_render();
    return false;
  });
  key.down('ctrl y', function() {
    list = ctrl_y(history);
    do_render();
    return false;
  });
  return ret;
};
