// Generated by CoffeeScript 1.3.3
var atHead, atTail, backspace, caret, clear, create_block, empty, found, inHead, inTail, input, insert_char, isArr, isCell, isStr, key_delete, last, move_left, move_right, point, show, spacebar,
  __slice = [].slice;

caret = '\t';

input = '<input value="sdfsdf"/>';

isArr = Array.isArray;

isStr = function(item) {
  return (typeof item) === 'string';
};

found = function(item) {
  return item.length > 0;
};

empty = function(item) {
  return item.length === 0;
};

point = function(item) {
  return (isStr(item)) && (item.indexOf(caret)) > -1;
};

show = function() {
  var args;
  args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
  return console.log.apply(console, args);
};

clear = function(item) {
  return item.replace(/\t/, '');
};

isCell = function(item) {
  if (isArr(item)) {
    if (item.length === 1) {
      if (item[0] === caret) {
        true;
      }
    }
  }
  return false;
};

atHead = function(item) {
  if (isStr(item)) {
    if (item[0] === caret) {
      return true;
    }
  }
  return false;
};

inHead = function(item) {
  if (isArr(item)) {
    if (item[0] === caret) {
      return true;
    }
  }
  return false;
};

last = function(item) {
  var len;
  len = item.length;
  return item[len - 1];
};

atTail = function(item) {
  if (isStr(item)) {
    if ((last(item)) === caret) {
      return true;
    }
  }
  return false;
};

inTail = function(item) {
  if (isArr(item)) {
    if ((last(item)) === caret) {
      return true;
    }
  }
  return false;
};

exports.insert_char = insert_char = function(list, char) {
  var ret;
  ret = [];
  list.forEach(function(item) {
    if (isStr(item)) {
      return ret.push(item.replace(/\t/, "" + char + "\t"));
    } else if (isArr(item)) {
      return ret.push(insert_char(item, char));
    } else {
      return ret.push(item);
    }
  });
  return ret;
};

exports.backspace = backspace = function(list) {
  var ret;
  ret = [];
  list.forEach(function(item) {
    var res;
    if (item === caret) {
      if (empty(item)) {
        return ret.push(caret);
      } else {
        ret.pop();
        return ret.push(caret);
      }
    } else if (isStr(item)) {
      res = item.replace(/.{1}\t/, caret);
      return ret.push(res);
    } else if (isCell(item)) {
      return ret.push(caret);
    } else if (isArr) {
      return ret.push(backspace(item));
    }
  });
  return ret;
};

exports.insert_blank = function(list) {
  return insert_char(list, ' ');
};

exports.create_block = create_block = function(list) {
  var ret;
  ret = [];
  list.forEach(function(item) {
    if (isArr(item)) {
      return ret.push(create_block(item));
    } else if (point(item)) {
      if (found(clear(item))) {
        ret.push(clear(item));
      }
      return ret.push([caret]);
    } else {
      return ret.push(item);
    }
  });
  return ret;
};

exports.spacebar = spacebar = function(list) {
  var ret;
  ret = [];
  list.forEach(function(item) {
    if (isArr(item)) {
      return ret.push(spacebar(item));
    } else if (item === caret) {
      return ret.push(caret);
    } else if (point(item)) {
      return ret.push(clear(item), caret);
    } else {
      return ret.push(item);
    }
  });
  return ret;
};

exports.page_up = function(list) {
  return list;
};

exports.page_down = function(list) {
  return list;
};

exports.move_end = function(list) {
  return list;
};

exports.move_home = function(list) {
  return list;
};

exports.move_left = move_left = function(list) {
  var ret;
  ret = [];
  list.forEach(function(item) {
    var tail;
    if (item === caret) {
      tail = ret.pop();
      if (tail != null) {
        if (isArr(tail)) {
          tail.push(caret);
        } else if (isStr(tail)) {
          tail = tail.concat(caret);
        }
        return ret.push(tail);
      } else {
        return ret.push(caret);
      }
    } else if (inHead(item)) {
      ret.push(caret);
      item.shift();
      if (found(item)) {
        return ret.push(move_left(item));
      }
    } else if (isArr(item)) {
      return ret.push(move_left(item));
    } else if (atHead(item)) {
      return ret.push(caret, item.slice(1));
    } else if (point(item)) {
      return ret.push(item.replace(/(.)(\t)/, "$2$1"));
    } else {
      return ret.push(item);
    }
  });
  return ret;
};

exports.move_right = move_right = function(list) {
  var mark, ret;
  ret = [];
  mark = false;
  list.forEach(function(item) {
    if (item === caret) {
      return mark = true;
    } else if (isStr(item)) {
      if (mark) {
        ret.push(caret.concat(item));
        return mark = false;
      } else if (atTail(item)) {
        return ret.push(item.slice(0, item.length - 1), caret);
      } else {
        return ret.push(item.replace(/(\t)(.)/, "$2$1"));
      }
    } else if (isArr(item)) {
      if (mark) {
        item.unshift(caret);
        ret.push(item);
        return mark = false;
      } else if (inTail(item)) {
        ret.push(item.slice(0, item.length - 1));
        return ret.push(caret);
      } else {
        return ret.push(move_right(item));
      }
    }
  });
  if (mark) {
    ret.push(caret);
  }
  return ret;
};

exports.move_up = function(list) {
  return list;
};

exports.move_down = function(list) {
  return list;
};

exports.key_insert = function(list) {
  var str;
  str = prompt() || '';
  return insert_char(list, str);
};

exports.key_delete = key_delete = function(list) {
  var ret;
  ret = [];
  list.forEach(function(item) {
    var tail;
    if (item === caret) {
      tail = ret.pop();
      return ret.push((tail != null ? tail.concat(caret) : caret));
    } else if (point(item)) {
      return ret.push(caret);
    } else if (isCell(item)) {
      return ret.push(caret);
    } else if (isArr(item)) {
      return ret.push(key_delete(item));
    } else {
      return ret.push(item);
    }
  });
  return ret;
};

exports.ctrl_m = function(list) {
  return list;
};

exports.ctrl_y = function(list) {
  return list;
};

exports.ctrl_p = function(list) {
  return list;
};
