// Generated by CoffeeScript 1.3.3
var backspace, caret, empty, found, insert_char, isArr, isStr, point, show,
  __slice = [].slice;

caret = '\t';

isArr = Array.isArray;

isStr = function(item) {
  return (typeof item) === 'string';
};

found = function(item) {
  return item.length > 0;
};

empty = function(item) {
  return item.length === 0;
};

point = function(item) {
  return (item.indexOf(caret)) > -1;
};

show = function() {
  var args;
  args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
  return console.log.apply(console, args);
};

exports.insert_char = insert_char = function(list, char) {
  var ret;
  ret = [];
  list.forEach(function(item) {
    if (isStr(item)) {
      return ret.push(item.replace(/\t/, "" + char + "\t"));
    } else if (isArr(item)) {
      return ret.push(insert_char(item, char));
    } else {
      return ret.push(item);
    }
  });
  return ret;
};

exports.backspace = backspace = function(list) {
  var ret;
  ret = [];
  list.forEach(function(item) {
    var res;
    if (item === caret) {
      if (empty(item)) {
        return ret.push(caret);
      } else {
        ret.pop();
        return ret.push(caret);
      }
    } else if (isStr(item)) {
      res = item.replace(/.{1}\t/, caret);
      return ret.push(res);
    } else if (isArr) {
      return ret.push(backspace(item));
    }
  });
  return ret;
};

exports.insert_blank = function(list) {
  return insert_char(list, ' ');
};

exports.create_block = function(list) {
  return list;
};

exports.spacebar = function(list) {
  return list;
};

exports.page_up = function(list) {
  return list;
};

exports.page_down = function(list) {
  return list;
};

exports.move_end = function(list) {
  return list;
};

exports.moe_end = function(list) {
  return list;
};

exports.move_left = function(list) {
  return list;
};

exports.move_right = function(list) {
  return list;
};

exports.move_up = function(list) {
  return list;
};

exports.move_down = function(list) {
  return list;
};

exports.key_insert = function(list) {
  return list;
};

exports.key_delete = function(list) {
  return list;
};

exports.ctrl_m = function(list) {
  return list;
};

exports.ctrl_y = function(list) {
  return list;
};

exports.ctrl_p = function(list) {
  return list;
};
