// Generated by CoffeeScript 1.3.3

$(function() {
  var click_choose, cursor, ed, editable;
  editable = 'contenteditable';
  cursor = "<code id='live' " + editable + "='true'></code>";
  ed = $('#editor');
  ed.append(cursor);
  $('#live').focus();
  ed.click(function() {
    return (function() {
      return $('#live').focus();
    })();
  });
  click_choose = function(elems) {
    return elems.click(function() {
      var old;
      old = $('#live').removeAttr(editable).removeAttr('id');
      click_choose(old);
      return elems.attr(editable, 'true').attr('id', 'live');
    });
  };
  return $(document).keydown(function(e) {
    var old, _ref;
    switch (e.keyCode) {
      case 13:
        console.log('xx');
        break;
      case 9:
        if ($('#live').html().length > 0) {
          $('#live').after(cursor);
          old = $('#live').first();
          old.removeAttr(editable).removeAttr('id');
          click_choose(old);
          $('#live').focus();
        }
    }
    if ((_ref = e.keyCode) === 9 || _ref === 13) {
      return false;
    }
  });
});
