// Generated by CoffeeScript 1.3.3
var caret, draw, escape, isArr, isStr;

isArr = Array.isArray;

isStr = function(item) {
  return (typeof item) === 'string';
};

escape = function(item) {
  return item.replace(/\s/g, '&nbsp;');
};

caret = '<span id="caret"></span>';

draw = function(list) {
  var html;
  html = '';
  list.forEach(function(item) {
    return html += isArr(item) ? draw(item) : isStr(item) ? "<code>" + (item.replace(/\t/, caret)) + "</code>" : "<code>" + (escape(item)) + "</code>";
  });
  return "<pre>" + html + "</pre>";
};

exports.render = function(list, elem) {
  return elem.html(draw(list));
};
