// Generated by CoffeeScript 1.3.3
var ls, show,
  __slice = [].slice;

show = function() {
  var args;
  args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
  return console.log.apply(console, args);
};

ls = localStorage;

$(function() {
  var cirru, editor, list;
  cirru = require('./cirru-editor.js');
  editor = cirru.editor($('#editor'));
  list = ls.list != null ? (JSON.parse(ls.list)).value : (ls.list = JSON.stringify({
    value: ['\t']
  }), ['\t']);
  editor.val(list);
  editor.render();
  editor.reset_history(list);
  editor.update(function() {
    return ls.list = JSON.stringify({
      value: editor.val()
    });
  });
  return $('#editor').click();
});
