// Generated by CoffeeScript 1.4.0
var __slice = [].slice;

define(function(require, exports) {
  var cirru, editor, show;
  show = function() {
    var args;
    args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    return console.log.apply(console, args);
  };
  cirru = require('../src/cirru-editor.js');
  editor = cirru.editor('editor');
  document.querySelector('#another').onclick = function() {
    return show(editor.value, editor.val());
  };
});
